########## basics ##########
--daemonize=true
--pid_file=@NEBULA_DATA_DIR@/pids/nebula-standalone.pid
--enable_optimizer=true
--default_charset=utf8
--default_collate=utf8_bin
--local_config=true

########## logging ##########
--log_dir=@NEBULA_DATA_DIR@/logs
--minloglevel=0
--v=0
--logbufsecs=0
--redirect_stdout=true
--stdout_log_file=standalone-stdout.log
--stderr_log_file=standalone-stderr.log
--stderrthreshold=3
--log_clean_days=0

########## query ##########
--accept_partial_success=false
--max_allowed_query_size=4194304

########## networking ##########
# RocksDB baseline bench: default standalone ports
--meta_server_addrs=127.0.0.1:9559
--local_ip=127.0.0.1
--listen_netdev=any
--port=9669
--meta_port=9559
--storage_port=9779
--reuse_port=false
--listen_backlog=1024
--client_idle_timeout_secs=28800
--session_idle_timeout_secs=28800
--num_accept_threads=1
--num_netio_threads=0
--num_worker_threads=0
--ws_ip=0.0.0.0
--ws_http_port=19669
--storage_client_timeout_ms=60000
--ws_meta_http_port=19559
--ws_storage_http_port=19779
--heartbeat_interval_secs=10

########## authentication ##########
--enable_authorize=false
--auth_type=password

########## memory ##########
--system_memory_high_watermark_ratio=0.8

########## experimental feature ##########
--enable_experimental_feature=false
--enable_data_balance=true

######### Raft #########
--raft_heartbeat_interval_secs=30
--raft_rpc_timeout_ms=500
--wal_ttl=14400

########## Disk ##########
--data_path=@NEBULA_DATA_DIR@/storage
--minimum_reserved_bytes=268435456
--rocksdb_batch_size=4096
--rocksdb_block_cache=4
--engine_type=rocksdb
--rocksdb_compression=snappy
--rocksdb_compression_per_level=
--enable_rocksdb_statistics=false
--rocksdb_stats_level=kExceptHistogramOrTimers
--enable_rocksdb_prefix_filtering=true
--enable_rocksdb_whole_key_filtering=false

############## rocksdb Options ##############
--rocksdb_db_options={}
--rocksdb_column_family_options={"write_buffer_size":"67108864","max_write_buffer_number":"4","max_bytes_for_level_base":"268435456"}
--rocksdb_block_based_table_options={"block_size":"8192"}

############## meta Options ##############
--meta_data_path=@NEBULA_DATA_DIR@/meta
--default_replica_factor=1
--default_parts_num=10
